### ISSUE TITLE
Demo Hangs After Login on Subscribe

### ISSUE THREAD

**Issue by thnk2wn** [ringcentral/ringcentral-call-control-js#46]
Cloned repo, yarn, yarn build, yarn start, logged in but hangs indefinitely...

![2022-10-06_11-32-05](https://user-images.githubusercontent.com/120529/194355748-e2f4b245-8f10-4a8b-81d3-ac6a4734bfb4.jpg)

**Comment by embbnux** [comment]
Hi @thnk2wn Thanks for reporting the issue. Do you get any error at Chrome "Console" panel? 
The network that you showed is normal as this is a long pull request for server event.

**Comment by embbnux** [comment]
Found the root cause. And it is fix at #47.  You can also get online demo here https://ringcentral.github.io/ringcentral-call-control-js/

**Comment by thnk2wn** [comment]
Thanks! It only happened for me the first time and then sporadically after that.
